server:
   port: 9000
spring:
   kafka:
      bootstrap-servers: localhost:9092
      topic-name: topic1
      topic-name2: topic2
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
         group-id: group1
         auto-offset-reset: earliest